### ISSUE TITLE
Updates to CI

### ISSUE THREAD

**Issue by makeclean** [svalinn/DAGMC-CI#41]
With the closue of DAGMC issue github/svalinn/dagmc/pull/350, there will be two tests files that are not currently being tested. 

test_TrackLengthMeshTally
uwuw_unit_tests_tally

These should be added to both nightly and build on demand tests.

**Comment by julry** [comment]
Looks like the tests ran fine:

http://submit-1.batlab.org/nmi/results/details?runID=312689

I'll update dagmc-ci and then merge dagmc pr #350


On 04/03/2015 09:26 AM, Andrew Davis wrote:
>
> Assigned #41 <https://github.com/svalinn/DAGMC-CI/issues/41> to @julry 
> <https://github.com/julry>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/svalinn/DAGMC-CI/issues/41#event-272701395>.
>

-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Julie C. Zachman
Department of Engineering Physics
jczachman@wisc.edu
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
